name: Update Stats Cards

on:
  schedule:
    - cron: "0 3 * * *" # Se ejecuta todos los días a las 3am
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # 1. Generar la tarjeta de Estadísticas Generales
      - name: Generate General Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          # Copié tus opciones: theme=github_dark, show_icons=true
          options: username=SoyFabianRG&theme=github_dark&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Generar la tarjeta de Top Lenguajes
      - name: Generate Top Langs
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          # Copié tus opciones: theme=github_dark, layout=compact, langs_count=10
          options: username=SoyFabianRG&theme=github_dark&layout=compact&langs_count=10
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # 3. Guardar los cambios en tu repo
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update stats cards" || exit 0
          git push
