name: Update Stats Cards

on:
  schedule:
    - cron: "0 3 * * *" # Se ejecuta todos los días a las 3am
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para trabajar con múltiples ramas

      # Cambiar a la rama output
      - name: Switch to output branch
        run: |
          git fetch origin output:output || git checkout -b output
          git checkout output

      # 1. Generar la tarjeta de Estadísticas Generales
      - name: Generate General Stats
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=SoyFabianRG&theme=catppuccin_mocha&show_icons=true
          path: stats.svg # Ahora en la raíz de output
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Generar la tarjeta de Top Lenguajes
      - name: Generate Top Langs
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=SoyFabianRG&theme=catppuccin_mocha&layout=compact&langs_count=10
          path: top-langs.svg # Ahora en la raíz de output
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=SoyFabianRG&repo=Plantillas-UNAM&show_icons=true&theme=catppuccin_mocha
          path: pin-plantillas-unam.svg # Ahora en la raíz de output
          token: ${{ secrets.GITHUB_TOKEN }}

      # 3. Guardar los cambios en la rama output
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.svg
          git commit -m "Update stats cards" || exit 0
          git push origin output  # Push explícito a la rama output
